# Generated by Django 3.0.4 on 2020-03-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
