# Generated by Django 3.0.4 on 2020-04-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boon', '0003_auto_20200416_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tax',
            old_name='name',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='tax',
            old_name='cess',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='tax',
            old_name='info',
            new_name='remarks',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='percentage',
        ),
        migrations.AddField(
            model_name='tax',
            name='dateFrom',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tax',
            name='dateTo',
            field=models.DateField(null=True),
        ),
    ]
