# Generated by Django 3.0.4 on 2020-04-30 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boon', '0004_auto_20200424_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucheritem',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boon.Brandmaster'),
        ),
        migrations.AlterField(
            model_name='categorymaster',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='materialpurchase',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boon.ItemMaster'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boon.ItemMaster'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='remarks',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tax',
            name='shortCode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
