# Generated by Django 3.0.4 on 2020-05-04 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boon', '0005_auto_20200430_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='itemmaster',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='itemmaster',
            name='taxCategory',
        ),
        migrations.RemoveField(
            model_name='partyaddressbook',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='partyaddressbook',
            name='place',
        ),
        migrations.RemoveField(
            model_name='purchasevoucher',
            name='address',
        ),
        migrations.RemoveField(
            model_name='purchasevoucher',
            name='suppiler',
        ),
        migrations.AddField(
            model_name='purchasevoucher',
            name='supplier',
            field=models.ForeignKey(max_length=502, null=True, on_delete=django.db.models.deletion.PROTECT, to='boon.Supplierdetails'),
        ),
        migrations.AddField(
            model_name='supplierdetails',
            name='contactID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='boon.PartyAddressBook'),
        ),
        migrations.AddField(
            model_name='supplierdetails',
            name='supplierType',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='contactID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='boon.PartyAddressBook'),
        ),
        migrations.DeleteModel(
            name='Suppliers',
        ),
        migrations.AddField(
            model_name='partyaddressbook',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='boon.Location'),
        ),
        migrations.AddField(
            model_name='stock',
            name='stockLocation',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.PROTECT, to='boon.Location'),
        ),
    ]
