# Generated by Django 3.0.4 on 2020-05-13 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boon', '0006_auto_20200504_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortCode', models.CharField(blank=True, max_length=50)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=6)),
                ('remarks', models.CharField(blank=True, max_length=50)),
                ('tax', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT, to='boon.Tax')),
            ],
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='taxCategory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='boon.TaxCategory'),
            preserve_default=False,
        ),
    ]
