# Generated by Django 3.0.4 on 2020-05-13 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boon', '0010_auto_20200513_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxcategory',
            old_name='categoryType',
            new_name='hsnCode',
        ),
    ]
