# Generated by Django 3.0.4 on 2020-05-13 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boon', '0011_auto_20200513_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmaster',
            name='taxCategory',
        ),
        migrations.RemoveField(
            model_name='taxcategory',
            name='rate',
        ),
    ]
