# Generated by Django 3.0.4 on 2020-05-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boon', '0012_auto_20200513_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucheritem',
            name='rate',
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='recoderLevel',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10),
        ),
    ]
