# Generated by Django 3.0.4 on 2020-05-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boon', '0013_auto_20200513_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tax',
            name='shortCode',
        ),
        migrations.AlterField(
            model_name='units',
            name='allowFractions',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
