# Generated by Django 3.0.4 on 2020-05-14 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boon', '0014_auto_20200514_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucheritem',
            name='discAmt',
        ),
        migrations.RemoveField(
            model_name='voucheritem',
            name='taxPct',
        ),
    ]
