# Generated by Django 3.0.4 on 2020-05-19 05:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boon', '0017_itemmaster_unitrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesVoucher',
            fields=[
                ('voucherId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('tin', models.CharField(max_length=50)),
                ('typee', models.CharField(choices=[('RS', 'Retail Sale'), ('B2B', 'Business to Business')], max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=4, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('rounding', models.DecimalField(decimal_places=4, max_digits=10)),
                ('recieved', models.DecimalField(decimal_places=4, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=4, max_digits=10)),
                ('netBalance', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='emailaddresses',
            name='contactID',
        ),
        migrations.RemoveField(
            model_name='extraaddresses',
            name='contactID',
        ),
        migrations.RemoveField(
            model_name='materialpurchase',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='materialpurchase',
            name='suppilerId',
        ),
        migrations.RemoveField(
            model_name='phonenumbers',
            name='contactID',
        ),
        migrations.RemoveField(
            model_name='voucheritem',
            name='discount',
        ),
        migrations.AddField(
            model_name='voucheritem',
            name='unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='boon.Units'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='EmailAddresses',
        ),
        migrations.DeleteModel(
            name='ExtraAddresses',
        ),
        migrations.DeleteModel(
            name='Materialpurchase',
        ),
        migrations.DeleteModel(
            name='PhoneNumbers',
        ),
        migrations.AlterField(
            model_name='voucheritem',
            name='voucherno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='boon.SalesVoucher'),
        ),
        migrations.DeleteModel(
            name='sales_voucher',
        ),
    ]
