# Generated by Django 3.0.4 on 2020-06-02 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boon', '0020_auto_20200601_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmaster',
            name='baseUnit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='boon.Units'),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='company',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='packingQty',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10),
        ),
    ]
