# Generated by Django 3.0.4 on 2020-06-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boon', '0021_auto_20200602_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucheritem',
            name='id',
        ),
        migrations.RemoveField(
            model_name='voucheritem',
            name='size',
        ),
        migrations.AlterField(
            model_name='voucheritem',
            name='itemNo',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
